/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as ThumbnailRouteImport } from './routes/thumbnail'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WTokenRouteImport } from './routes/w.$token'
import { Route as RequestOrgSlugRouteImport } from './routes/request.$orgSlug'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AppWelcomeRouteImport } from './routes/_app/welcome'
import { Route as AppTemplatesRouteImport } from './routes/_app/templates'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppRequestsRouteImport } from './routes/_app/requests'
import { Route as AppLeadsRouteImport } from './routes/_app/leads'
import { Route as AppIntegrationsRouteImport } from './routes/_app/integrations'
import { Route as AppFunnelRouteImport } from './routes/_app/funnel'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppConnectorsRouteImport } from './routes/_app/connectors'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppWorkspacesIndexRouteImport } from './routes/_app/workspaces/index'
import { Route as AppToolsIndexRouteImport } from './routes/_app/tools/index'
import { Route as AppCampaignsIndexRouteImport } from './routes/_app/campaigns/index'
import { Route as RequestStatusTokenRouteImport } from './routes/request.status.$token'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as IntakeOrgSlugHackathonRouteImport } from './routes/intake.$orgSlug.hackathon'
import { Route as AppWorkspacesIdRouteImport } from './routes/_app/workspaces/$id'
import { Route as AppToolsUtmRouteImport } from './routes/_app/tools/utm'
import { Route as AppToolsTaxonomyRouteImport } from './routes/_app/tools/taxonomy'
import { Route as AppToolsListCleanerRouteImport } from './routes/_app/tools/list-cleaner'
import { Route as AppToolsImportRouteImport } from './routes/_app/tools/import'
import { Route as AppToolsFunnelTargetsRouteImport } from './routes/_app/tools/funnel-targets'
import { Route as AppToolsEventsRouteImport } from './routes/_app/tools/events'
import { Route as AppToolsEventIntakeRouteImport } from './routes/_app/tools/event-intake'
import { Route as AppToolsCampaignPerformanceRouteImport } from './routes/_app/tools/campaign-performance'
import { Route as AppToolsCampaignInABoxRouteImport } from './routes/_app/tools/campaign-in-a-box'
import { Route as AppToolsCampaignCreatorRouteImport } from './routes/_app/tools/campaign-creator'
import { Route as AppToolsAllUtmsRouteImport } from './routes/_app/tools/all-utms'
import { Route as AppToolsSplatRouteImport } from './routes/_app/tools/$'
import { Route as AppCampaignsIdRouteImport } from './routes/_app/campaigns/$id'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicCronDailyDigestRouteImport } from './routes/api/public/cron/daily-digest'
import { Route as ApiPublicCronClusterRetrosRouteImport } from './routes/api/public/cron/cluster-retros'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ThumbnailRoute = ThumbnailRouteImport.update({
  id: '/thumbnail',
  path: '/thumbnail',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WTokenRoute = WTokenRouteImport.update({
  id: '/w/$token',
  path: '/w/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestOrgSlugRoute = RequestOrgSlugRouteImport.update({
  id: '/request/$orgSlug',
  path: '/request/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWelcomeRoute = AppWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsRoute = AppRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppFunnelRoute = AppFunnelRouteImport.update({
  id: '/funnel',
  path: '/funnel',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectorsRoute = AppConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspacesIndexRoute = AppWorkspacesIndexRouteImport.update({
  id: '/workspaces/',
  path: '/workspaces/',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsIndexRoute = AppToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsIndexRoute = AppCampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => AppRoute,
} as any)
const RequestStatusTokenRoute = RequestStatusTokenRouteImport.update({
  id: '/request/status/$token',
  path: '/request/status/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeOrgSlugHackathonRoute = IntakeOrgSlugHackathonRouteImport.update({
  id: '/intake/$orgSlug/hackathon',
  path: '/intake/$orgSlug/hackathon',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspacesIdRoute = AppWorkspacesIdRouteImport.update({
  id: '/workspaces/$id',
  path: '/workspaces/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsUtmRoute = AppToolsUtmRouteImport.update({
  id: '/tools/utm',
  path: '/tools/utm',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsTaxonomyRoute = AppToolsTaxonomyRouteImport.update({
  id: '/tools/taxonomy',
  path: '/tools/taxonomy',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsListCleanerRoute = AppToolsListCleanerRouteImport.update({
  id: '/tools/list-cleaner',
  path: '/tools/list-cleaner',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsImportRoute = AppToolsImportRouteImport.update({
  id: '/tools/import',
  path: '/tools/import',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsFunnelTargetsRoute = AppToolsFunnelTargetsRouteImport.update({
  id: '/tools/funnel-targets',
  path: '/tools/funnel-targets',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsEventsRoute = AppToolsEventsRouteImport.update({
  id: '/tools/events',
  path: '/tools/events',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsEventIntakeRoute = AppToolsEventIntakeRouteImport.update({
  id: '/tools/event-intake',
  path: '/tools/event-intake',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsCampaignPerformanceRoute =
  AppToolsCampaignPerformanceRouteImport.update({
    id: '/tools/campaign-performance',
    path: '/tools/campaign-performance',
    getParentRoute: () => AppRoute,
  } as any)
const AppToolsCampaignInABoxRoute = AppToolsCampaignInABoxRouteImport.update({
  id: '/tools/campaign-in-a-box',
  path: '/tools/campaign-in-a-box',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsCampaignCreatorRoute = AppToolsCampaignCreatorRouteImport.update({
  id: '/tools/campaign-creator',
  path: '/tools/campaign-creator',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsAllUtmsRoute = AppToolsAllUtmsRouteImport.update({
  id: '/tools/all-utms',
  path: '/tools/all-utms',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsSplatRoute = AppToolsSplatRouteImport.update({
  id: '/tools/$',
  path: '/tools/$',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsIdRoute = AppCampaignsIdRouteImport.update({
  id: '/campaigns/$id',
  path: '/campaigns/$id',
  getParentRoute: () => AppRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronDailyDigestRoute =
  ApiPublicCronDailyDigestRouteImport.update({
    id: '/api/public/cron/daily-digest',
    path: '/api/public/cron/daily-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronClusterRetrosRoute =
  ApiPublicCronClusterRetrosRouteImport.update({
    id: '/api/public/cron/cluster-retros',
    path: '/api/public/cron/cluster-retros',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/thumbnail': typeof ThumbnailRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/calendar': typeof AppCalendarRoute
  '/connectors': typeof AppConnectorsRoute
  '/dashboard': typeof AppDashboardRoute
  '/funnel': typeof AppFunnelRoute
  '/integrations': typeof AppIntegrationsRoute
  '/leads': typeof AppLeadsRoute
  '/requests': typeof AppRequestsRoute
  '/settings': typeof AppSettingsRoute
  '/templates': typeof AppTemplatesRoute
  '/welcome': typeof AppWelcomeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/invite/$token': typeof InviteTokenRoute
  '/r/$slug': typeof RSlugRoute
  '/request/$orgSlug': typeof RequestOrgSlugRoute
  '/w/$token': typeof WTokenRoute
  '/campaigns/$id': typeof AppCampaignsIdRoute
  '/tools/$': typeof AppToolsSplatRoute
  '/tools/all-utms': typeof AppToolsAllUtmsRoute
  '/tools/campaign-creator': typeof AppToolsCampaignCreatorRoute
  '/tools/campaign-in-a-box': typeof AppToolsCampaignInABoxRoute
  '/tools/campaign-performance': typeof AppToolsCampaignPerformanceRoute
  '/tools/event-intake': typeof AppToolsEventIntakeRoute
  '/tools/events': typeof AppToolsEventsRoute
  '/tools/funnel-targets': typeof AppToolsFunnelTargetsRoute
  '/tools/import': typeof AppToolsImportRoute
  '/tools/list-cleaner': typeof AppToolsListCleanerRoute
  '/tools/taxonomy': typeof AppToolsTaxonomyRoute
  '/tools/utm': typeof AppToolsUtmRoute
  '/workspaces/$id': typeof AppWorkspacesIdRoute
  '/intake/$orgSlug/hackathon': typeof IntakeOrgSlugHackathonRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/request/status/$token': typeof RequestStatusTokenRoute
  '/campaigns/': typeof AppCampaignsIndexRoute
  '/tools/': typeof AppToolsIndexRoute
  '/workspaces/': typeof AppWorkspacesIndexRoute
  '/api/public/cron/cluster-retros': typeof ApiPublicCronClusterRetrosRoute
  '/api/public/cron/daily-digest': typeof ApiPublicCronDailyDigestRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/thumbnail': typeof ThumbnailRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/calendar': typeof AppCalendarRoute
  '/connectors': typeof AppConnectorsRoute
  '/dashboard': typeof AppDashboardRoute
  '/funnel': typeof AppFunnelRoute
  '/integrations': typeof AppIntegrationsRoute
  '/leads': typeof AppLeadsRoute
  '/requests': typeof AppRequestsRoute
  '/settings': typeof AppSettingsRoute
  '/templates': typeof AppTemplatesRoute
  '/welcome': typeof AppWelcomeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/invite/$token': typeof InviteTokenRoute
  '/r/$slug': typeof RSlugRoute
  '/request/$orgSlug': typeof RequestOrgSlugRoute
  '/w/$token': typeof WTokenRoute
  '/campaigns/$id': typeof AppCampaignsIdRoute
  '/tools/$': typeof AppToolsSplatRoute
  '/tools/all-utms': typeof AppToolsAllUtmsRoute
  '/tools/campaign-creator': typeof AppToolsCampaignCreatorRoute
  '/tools/campaign-in-a-box': typeof AppToolsCampaignInABoxRoute
  '/tools/campaign-performance': typeof AppToolsCampaignPerformanceRoute
  '/tools/event-intake': typeof AppToolsEventIntakeRoute
  '/tools/events': typeof AppToolsEventsRoute
  '/tools/funnel-targets': typeof AppToolsFunnelTargetsRoute
  '/tools/import': typeof AppToolsImportRoute
  '/tools/list-cleaner': typeof AppToolsListCleanerRoute
  '/tools/taxonomy': typeof AppToolsTaxonomyRoute
  '/tools/utm': typeof AppToolsUtmRoute
  '/workspaces/$id': typeof AppWorkspacesIdRoute
  '/intake/$orgSlug/hackathon': typeof IntakeOrgSlugHackathonRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/request/status/$token': typeof RequestStatusTokenRoute
  '/campaigns': typeof AppCampaignsIndexRoute
  '/tools': typeof AppToolsIndexRoute
  '/workspaces': typeof AppWorkspacesIndexRoute
  '/api/public/cron/cluster-retros': typeof ApiPublicCronClusterRetrosRoute
  '/api/public/cron/daily-digest': typeof ApiPublicCronDailyDigestRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/thumbnail': typeof ThumbnailRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/connectors': typeof AppConnectorsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/funnel': typeof AppFunnelRoute
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/leads': typeof AppLeadsRoute
  '/_app/requests': typeof AppRequestsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/templates': typeof AppTemplatesRoute
  '/_app/welcome': typeof AppWelcomeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/invite/$token': typeof InviteTokenRoute
  '/r/$slug': typeof RSlugRoute
  '/request/$orgSlug': typeof RequestOrgSlugRoute
  '/w/$token': typeof WTokenRoute
  '/_app/campaigns/$id': typeof AppCampaignsIdRoute
  '/_app/tools/$': typeof AppToolsSplatRoute
  '/_app/tools/all-utms': typeof AppToolsAllUtmsRoute
  '/_app/tools/campaign-creator': typeof AppToolsCampaignCreatorRoute
  '/_app/tools/campaign-in-a-box': typeof AppToolsCampaignInABoxRoute
  '/_app/tools/campaign-performance': typeof AppToolsCampaignPerformanceRoute
  '/_app/tools/event-intake': typeof AppToolsEventIntakeRoute
  '/_app/tools/events': typeof AppToolsEventsRoute
  '/_app/tools/funnel-targets': typeof AppToolsFunnelTargetsRoute
  '/_app/tools/import': typeof AppToolsImportRoute
  '/_app/tools/list-cleaner': typeof AppToolsListCleanerRoute
  '/_app/tools/taxonomy': typeof AppToolsTaxonomyRoute
  '/_app/tools/utm': typeof AppToolsUtmRoute
  '/_app/workspaces/$id': typeof AppWorkspacesIdRoute
  '/intake/$orgSlug/hackathon': typeof IntakeOrgSlugHackathonRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/request/status/$token': typeof RequestStatusTokenRoute
  '/_app/campaigns/': typeof AppCampaignsIndexRoute
  '/_app/tools/': typeof AppToolsIndexRoute
  '/_app/workspaces/': typeof AppWorkspacesIndexRoute
  '/api/public/cron/cluster-retros': typeof ApiPublicCronClusterRetrosRoute
  '/api/public/cron/daily-digest': typeof ApiPublicCronDailyDigestRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/login'
    | '/reset-password'
    | '/thumbnail'
    | '/unsubscribe'
    | '/calendar'
    | '/connectors'
    | '/dashboard'
    | '/funnel'
    | '/integrations'
    | '/leads'
    | '/requests'
    | '/settings'
    | '/templates'
    | '/welcome'
    | '/email/unsubscribe'
    | '/invite/$token'
    | '/r/$slug'
    | '/request/$orgSlug'
    | '/w/$token'
    | '/campaigns/$id'
    | '/tools/$'
    | '/tools/all-utms'
    | '/tools/campaign-creator'
    | '/tools/campaign-in-a-box'
    | '/tools/campaign-performance'
    | '/tools/event-intake'
    | '/tools/events'
    | '/tools/funnel-targets'
    | '/tools/import'
    | '/tools/list-cleaner'
    | '/tools/taxonomy'
    | '/tools/utm'
    | '/workspaces/$id'
    | '/intake/$orgSlug/hackathon'
    | '/lovable/email/suppression'
    | '/request/status/$token'
    | '/campaigns/'
    | '/tools/'
    | '/workspaces/'
    | '/api/public/cron/cluster-retros'
    | '/api/public/cron/daily-digest'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/login'
    | '/reset-password'
    | '/thumbnail'
    | '/unsubscribe'
    | '/calendar'
    | '/connectors'
    | '/dashboard'
    | '/funnel'
    | '/integrations'
    | '/leads'
    | '/requests'
    | '/settings'
    | '/templates'
    | '/welcome'
    | '/email/unsubscribe'
    | '/invite/$token'
    | '/r/$slug'
    | '/request/$orgSlug'
    | '/w/$token'
    | '/campaigns/$id'
    | '/tools/$'
    | '/tools/all-utms'
    | '/tools/campaign-creator'
    | '/tools/campaign-in-a-box'
    | '/tools/campaign-performance'
    | '/tools/event-intake'
    | '/tools/events'
    | '/tools/funnel-targets'
    | '/tools/import'
    | '/tools/list-cleaner'
    | '/tools/taxonomy'
    | '/tools/utm'
    | '/workspaces/$id'
    | '/intake/$orgSlug/hackathon'
    | '/lovable/email/suppression'
    | '/request/status/$token'
    | '/campaigns'
    | '/tools'
    | '/workspaces'
    | '/api/public/cron/cluster-retros'
    | '/api/public/cron/daily-digest'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_app'
    | '/login'
    | '/reset-password'
    | '/thumbnail'
    | '/unsubscribe'
    | '/_app/calendar'
    | '/_app/connectors'
    | '/_app/dashboard'
    | '/_app/funnel'
    | '/_app/integrations'
    | '/_app/leads'
    | '/_app/requests'
    | '/_app/settings'
    | '/_app/templates'
    | '/_app/welcome'
    | '/email/unsubscribe'
    | '/invite/$token'
    | '/r/$slug'
    | '/request/$orgSlug'
    | '/w/$token'
    | '/_app/campaigns/$id'
    | '/_app/tools/$'
    | '/_app/tools/all-utms'
    | '/_app/tools/campaign-creator'
    | '/_app/tools/campaign-in-a-box'
    | '/_app/tools/campaign-performance'
    | '/_app/tools/event-intake'
    | '/_app/tools/events'
    | '/_app/tools/funnel-targets'
    | '/_app/tools/import'
    | '/_app/tools/list-cleaner'
    | '/_app/tools/taxonomy'
    | '/_app/tools/utm'
    | '/_app/workspaces/$id'
    | '/intake/$orgSlug/hackathon'
    | '/lovable/email/suppression'
    | '/request/status/$token'
    | '/_app/campaigns/'
    | '/_app/tools/'
    | '/_app/workspaces/'
    | '/api/public/cron/cluster-retros'
    | '/api/public/cron/daily-digest'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ThumbnailRoute: typeof ThumbnailRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  InviteTokenRoute: typeof InviteTokenRoute
  RSlugRoute: typeof RSlugRoute
  RequestOrgSlugRoute: typeof RequestOrgSlugRoute
  WTokenRoute: typeof WTokenRoute
  IntakeOrgSlugHackathonRoute: typeof IntakeOrgSlugHackathonRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  RequestStatusTokenRoute: typeof RequestStatusTokenRoute
  ApiPublicCronClusterRetrosRoute: typeof ApiPublicCronClusterRetrosRoute
  ApiPublicCronDailyDigestRoute: typeof ApiPublicCronDailyDigestRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thumbnail': {
      id: '/thumbnail'
      path: '/thumbnail'
      fullPath: '/thumbnail'
      preLoaderRoute: typeof ThumbnailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$token': {
      id: '/w/$token'
      path: '/w/$token'
      fullPath: '/w/$token'
      preLoaderRoute: typeof WTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request/$orgSlug': {
      id: '/request/$orgSlug'
      path: '/request/$orgSlug'
      fullPath: '/request/$orgSlug'
      preLoaderRoute: typeof RequestOrgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/welcome': {
      id: '/_app/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AppWelcomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/requests': {
      id: '/_app/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AppRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/funnel': {
      id: '/_app/funnel'
      path: '/funnel'
      fullPath: '/funnel'
      preLoaderRoute: typeof AppFunnelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connectors': {
      id: '/_app/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof AppConnectorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspaces/': {
      id: '/_app/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof AppWorkspacesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools/': {
      id: '/_app/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof AppToolsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns/': {
      id: '/_app/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AppCampaignsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/request/status/$token': {
      id: '/request/status/$token'
      path: '/request/status/$token'
      fullPath: '/request/status/$token'
      preLoaderRoute: typeof RequestStatusTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/$orgSlug/hackathon': {
      id: '/intake/$orgSlug/hackathon'
      path: '/intake/$orgSlug/hackathon'
      fullPath: '/intake/$orgSlug/hackathon'
      preLoaderRoute: typeof IntakeOrgSlugHackathonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workspaces/$id': {
      id: '/_app/workspaces/$id'
      path: '/workspaces/$id'
      fullPath: '/workspaces/$id'
      preLoaderRoute: typeof AppWorkspacesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools/utm': {
      id: '/_app/tools/utm'
      path: '/tools/utm'
      fullPath: '/tools/utm'
      preLoaderRoute: typeof AppToolsUtmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools/taxonomy': {
      id: '/_app/tools/taxonomy'
      path: '/tools/taxonomy'
      fullPath: '/tools/taxonomy'
      preLoaderRoute: typeof AppToolsTaxonomyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools/list-cleaner': {
      id: '/_app/tools/list-cleaner'
      path: '/tools/list-cleaner'
      fullPath: '/tools/list-cleaner'
      preLoaderRoute: typeof AppToolsListCleanerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools/import': {
      id: '/_app/tools/import'
      path: '/tools/import'
      fullPath: '/tools/import'
      preLoaderRoute: typeof AppToolsImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools/funnel-targets': {
      id: '/_app/tools/funnel-targets'
      path: '/tools/funnel-targets'
      fullPath: '/tools/funnel-targets'
      preLoaderRoute: typeof AppToolsFunnelTargetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools/events': {
      id: '/_app/tools/events'
      path: '/tools/events'
      fullPath: '/tools/events'
      preLoaderRoute: typeof AppToolsEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools/event-intake': {
      id: '/_app/tools/event-intake'
      path: '/tools/event-intake'
      fullPath: '/tools/event-intake'
      preLoaderRoute: typeof AppToolsEventIntakeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools/campaign-performance': {
      id: '/_app/tools/campaign-performance'
      path: '/tools/campaign-performance'
      fullPath: '/tools/campaign-performance'
      preLoaderRoute: typeof AppToolsCampaignPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools/campaign-in-a-box': {
      id: '/_app/tools/campaign-in-a-box'
      path: '/tools/campaign-in-a-box'
      fullPath: '/tools/campaign-in-a-box'
      preLoaderRoute: typeof AppToolsCampaignInABoxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools/campaign-creator': {
      id: '/_app/tools/campaign-creator'
      path: '/tools/campaign-creator'
      fullPath: '/tools/campaign-creator'
      preLoaderRoute: typeof AppToolsCampaignCreatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools/all-utms': {
      id: '/_app/tools/all-utms'
      path: '/tools/all-utms'
      fullPath: '/tools/all-utms'
      preLoaderRoute: typeof AppToolsAllUtmsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools/$': {
      id: '/_app/tools/$'
      path: '/tools/$'
      fullPath: '/tools/$'
      preLoaderRoute: typeof AppToolsSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns/$id': {
      id: '/_app/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof AppCampaignsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/daily-digest': {
      id: '/api/public/cron/daily-digest'
      path: '/api/public/cron/daily-digest'
      fullPath: '/api/public/cron/daily-digest'
      preLoaderRoute: typeof ApiPublicCronDailyDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/cluster-retros': {
      id: '/api/public/cron/cluster-retros'
      path: '/api/public/cron/cluster-retros'
      fullPath: '/api/public/cron/cluster-retros'
      preLoaderRoute: typeof ApiPublicCronClusterRetrosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppConnectorsRoute: typeof AppConnectorsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFunnelRoute: typeof AppFunnelRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppRequestsRoute: typeof AppRequestsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppWelcomeRoute: typeof AppWelcomeRoute
  AppCampaignsIdRoute: typeof AppCampaignsIdRoute
  AppToolsSplatRoute: typeof AppToolsSplatRoute
  AppToolsAllUtmsRoute: typeof AppToolsAllUtmsRoute
  AppToolsCampaignCreatorRoute: typeof AppToolsCampaignCreatorRoute
  AppToolsCampaignInABoxRoute: typeof AppToolsCampaignInABoxRoute
  AppToolsCampaignPerformanceRoute: typeof AppToolsCampaignPerformanceRoute
  AppToolsEventIntakeRoute: typeof AppToolsEventIntakeRoute
  AppToolsEventsRoute: typeof AppToolsEventsRoute
  AppToolsFunnelTargetsRoute: typeof AppToolsFunnelTargetsRoute
  AppToolsImportRoute: typeof AppToolsImportRoute
  AppToolsListCleanerRoute: typeof AppToolsListCleanerRoute
  AppToolsTaxonomyRoute: typeof AppToolsTaxonomyRoute
  AppToolsUtmRoute: typeof AppToolsUtmRoute
  AppWorkspacesIdRoute: typeof AppWorkspacesIdRoute
  AppCampaignsIndexRoute: typeof AppCampaignsIndexRoute
  AppToolsIndexRoute: typeof AppToolsIndexRoute
  AppWorkspacesIndexRoute: typeof AppWorkspacesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppConnectorsRoute: AppConnectorsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFunnelRoute: AppFunnelRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppRequestsRoute: AppRequestsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppWelcomeRoute: AppWelcomeRoute,
  AppCampaignsIdRoute: AppCampaignsIdRoute,
  AppToolsSplatRoute: AppToolsSplatRoute,
  AppToolsAllUtmsRoute: AppToolsAllUtmsRoute,
  AppToolsCampaignCreatorRoute: AppToolsCampaignCreatorRoute,
  AppToolsCampaignInABoxRoute: AppToolsCampaignInABoxRoute,
  AppToolsCampaignPerformanceRoute: AppToolsCampaignPerformanceRoute,
  AppToolsEventIntakeRoute: AppToolsEventIntakeRoute,
  AppToolsEventsRoute: AppToolsEventsRoute,
  AppToolsFunnelTargetsRoute: AppToolsFunnelTargetsRoute,
  AppToolsImportRoute: AppToolsImportRoute,
  AppToolsListCleanerRoute: AppToolsListCleanerRoute,
  AppToolsTaxonomyRoute: AppToolsTaxonomyRoute,
  AppToolsUtmRoute: AppToolsUtmRoute,
  AppWorkspacesIdRoute: AppWorkspacesIdRoute,
  AppCampaignsIndexRoute: AppCampaignsIndexRoute,
  AppToolsIndexRoute: AppToolsIndexRoute,
  AppWorkspacesIndexRoute: AppWorkspacesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ThumbnailRoute: ThumbnailRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  InviteTokenRoute: InviteTokenRoute,
  RSlugRoute: RSlugRoute,
  RequestOrgSlugRoute: RequestOrgSlugRoute,
  WTokenRoute: WTokenRoute,
  IntakeOrgSlugHackathonRoute: IntakeOrgSlugHackathonRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  RequestStatusTokenRoute: RequestStatusTokenRoute,
  ApiPublicCronClusterRetrosRoute: ApiPublicCronClusterRetrosRoute,
  ApiPublicCronDailyDigestRoute: ApiPublicCronDailyDigestRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
